/**
 * Which structured filters each job site can honor in URL builders.
 * Unsupported dimensions are folded into keyword text (soft) in platformUrls.
 */

/** @typedef {{ location: boolean; experience: boolean; datePosted: boolean; remote: boolean; internship: boolean; company: boolean; salary: boolean; jobType: boolean }} PlatformCaps */

/** @type {Record<string, PlatformCaps>} */
export const platformCapabilities = {
  linkedin: {
    location: true,
    experience: true,
    datePosted: true,
    remote: true,
    internship: true,
    // LinkedIn job search does not reliably honor a separate company= param; fold into keywords instead.
    company: false,
    salary: false,
    jobType: true,
  },
  naukri: {
    location: true,
    experience: true,
    datePosted: false,
    remote: false,
    internship: true,
    company: false,
    salary: false,
    jobType: true,
  },
  indeed: {
    location: true,
    experience: true,
    datePosted: true,
    remote: true,
    internship: true,
    company: true,
    salary: true,
    jobType: true,
  },
  internshala: {
    location: true,
    experience: false,
    datePosted: false,
    remote: false,
    internship: true,
    company: false,
    salary: false,
    jobType: true,
  },
  foundit: {
    location: true,
    experience: true,
    datePosted: false,
    remote: false,
    internship: true,
    company: false,
    salary: false,
    jobType: true,
  },
  shine: {
    location: true,
    experience: true,
    datePosted: false,
    remote: false,
    internship: true,
    company: false,
    salary: false,
    jobType: true,
  },
  freshersworld: {
    location: true,
    experience: false,
    datePosted: false,
    remote: false,
    internship: true,
    company: false,
    salary: false,
    jobType: true,
  },
  cutshort: {
    location: true,
    experience: false,
    datePosted: false,
    remote: true,
    internship: true,
    company: false,
    salary: false,
    jobType: true,
  },
  wellfound: {
    location: true,
    experience: true,
    datePosted: false,
    remote: true,
    internship: true,
    company: false,
    salary: false,
    jobType: true,
  },
  timesjobs: {
    location: true,
    experience: true,
    datePosted: false,
    remote: false,
    internship: true,
    company: false,
    salary: false,
    jobType: true,
  },
  hirist: {
    location: true,
    experience: false,
    datePosted: false,
    remote: false,
    internship: true,
    company: false,
    salary: false,
    jobType: true,
  },
};
